public class TesteExcecao1 { public static void main (String args[]) throws Exception { try { new A().f(1); System.out.println("Depois do f no main"); } catch (TabajaraException e) { System.out.println(e.mensagem); } finally { System.out.println("Antes do fim do main"); } System.out.println("Fim"); } } public class TesteExcecao2 {  public static void main (String args[]) throws Exception { try { new A().f(2); System.out.println("Depois do f no main"); } catch (TabajaraException e) { System.out.println(e.mensagem); } finally { System.out.println("Antes do fim do main"); } System.out.println("Fim"); } } class A { void f(int i) throws Exception { try { System.out.println("In√≠cio de f"); new B(i).g(); System.out.println("Depois de g em f"); } catch(SidelmawException e) { System.out.println(e.mensagem); throw e; } System.out.println("Fim de f"); throw new Exception("Uma excecao generica"); } } class B { int x; B (int i) { x = i; } void g () throws TabajaraException { if (x == 2) throw new SidelmawException("Danou-se"); else throw new SiferrowException("Ferrou-se"); } } class SidelmawException extends TabajaraException { SidelmawException (String m) { super(m); } } class SiferrowException extends TabajaraException { SiferrowException (String m) { super(m); } } class TabajaraException extends Exception { String mensagem; TabajaraException (String msg) { mensagem = msg; } }